# Generated by Django 5.2.6 on 2025-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slowork', '0002_remove_job_category_remove_job_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksubmission',
            old_name='submitted_by',
            new_name='user',
        ),
    ]
