# Generated by Django 5.2.4 on 2025-10-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowork', '0003_alter_job_image_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
