# Generated by Django 5.2.4 on 2025-10-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slowork', '0006_worksubmission_change_request_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(related_name='jobs', to='slowork.jobcategory'),
        ),
    ]
