# Generated by Django 5.2.4 on 2025-10-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slowork', '0007_remove_job_category_job_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='categories',
            new_name='category',
        ),
    ]
